# fly.toml app configuration file generated for simple-slack on 2024-03-25T00:34:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-slack'
primary_region = 'ord'

[build]
  image = 'devatherock/simple-slack-api:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
