slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:latest
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  docker: circleci/docker@1.5.0

work_directory: &work_directory
  working_directory: ~/simple-slack

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    docker:
    - image: circleci/golang:1.14
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory  

version: 2.1
jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - sonarcloud/scan
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: make check
  build:
    executor: docker-executor
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: |
          make coveralls
          make build
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/simple-slack
          paths:
            - release

  publish_release:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/simple-slack
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull devatherock/simple-slack:$DEV_TAG
          docker tag devatherock/simple-slack:$DEV_TAG devatherock/simple-slack:$TAG
          docker push devatherock/simple-slack:$TAG

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f"

workflows:
  version: 2.1
  build_publish:
    jobs:
      - build:
          context:
            - docker-credentials
            - sonar-credentials
          filters:
            branches:
              only: master
      - docker/publish:
          name: publish
          executor: docker-executor
          context:
            - docker-credentials
          requires:
            - build
          image: devatherock/simple-slack  
          attach-at: ~/simple-slack
          tag: "${CIRCLE_SHA1:0:8},latest"
          use-remote-docker: true
          docker-username: DOCKER_USERNAME
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
  release:
    jobs:
      - publish_release:
          context:
            - docker-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish_release
  pr_check:
    jobs:
      - test:
          context:
            - docker-credentials
            - sonar-credentials
          filters:
            branches:
              ignore: master
