go_lang_image: &go_lang_image
  docker:
    - image: circleci/golang:1.14
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    
orbs:
  docker: circleci/docker@1.5.0

work_directory: &work_directory
  working_directory: ~/simple-slack

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    docker:
      - image: docker:19.03.6
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory  

version: 2.1
jobs:
  test:
    <<: *go_lang_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go vet
  build:
    <<: *go_lang_image
    <<: *resource_class
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -o release/simpleslack
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/simple-slack
          paths:
            - release

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run: /bin/simpleslack -c "#33ad7f"
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c"
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - build:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - docker/publish:
          context:
            - docker-credentials
          requires:
            - build
          image: devatherock/simple-slack  
          attach-at: ~/simple-slack
          tag: "0.4.0,latest"
          use-remote-docker: true
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - docker/publish
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - docker/publish
  pr_check:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
